# Generated by Django 3.2.5 on 2021-07-23 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1, 'Меньше 1 поставить нельзя')], verbose_name='время приготовления в минутах'),
        ),
    ]
