# Generated by Django 3.2.5 on 2021-08-12 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210727_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Меньше 1 поставить нельзя')], verbose_name='Количество ингредиента'),
        ),
    ]
