# Generated by Django 3.2.5 on 2021-09-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210901_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='resipe_set', through='recipes.IngredientRecipe', to='recipes.Ingredient'),
        ),
    ]
