# Generated by Django 3.2.5 on 2021-09-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
