# Generated by Django 3.2.5 on 2021-09-21 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20210913_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.CharField(default=1, max_length=200, validators=[django.core.validators.MinValueValidator(1, 'Меньше 1 поставить нельзя')], verbose_name='Количество ингредиента'),
        ),
    ]
