# Generated by Django 3.2.5 on 2021-09-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_ingredientrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество ингредиента'),
        ),
    ]
